# Site settings
title: 鱼虾写字
email: xuwei@fseasy.top
# GEM which uses `github-pages` depending on github repo. set this var is necessary when repo's `url` don't contain
# repository field. (such as, we change the dns name `github.com` => ip port in repo's url)
repository: fseasy/blog.git
description: > # this means to ignore newlines until "baseurl:"
  "one branch, one mud at a time, a lodge rises", said Haohao.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.fseasy.top" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
highlighter: none
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true # use prism.js to highlight instead

plugins: 
  - jekyll-paginate
  - jekyll-sitemap

exclude: [_site, md_templates_, deployment_, private_, scripts_, .claude]
paginate: 15

#social info
github_username: fseasy

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:title/

sass:
    style: compressed
    sass_dir: assets/css/_sass

# Used for Blog-extra-files, related to 
# - `_plugins/symlink_bef.rb`: local deploy symlink
# - `_includes/bef.html`: decide how to generate the bef link
# - sw-bef.js: decide which production service to use.
bef_process:
  force_gen_production_link: false  # set true to use production host (for SW testing)
  local:
    src: "../blog-extra-file" # relative to the `source` dir (root of the repo dir)
    dst: "bef" # relative to the target dir (`_site`)
  # Always generating this link in production HTML. then the sw-bef.js will 
  # hack this link to the actual services.
  production_gen_link: "https://bef.fseasy.top"
  production_service_alternative:
    cf_cdn:
      host: "https://bef.fseasy.top" # cloudflare CDN. too slow in evening
      connect_timeout_ms: 1500
    vercel:
      host: "https://bef-vercel.fseasy.top" # worse, totally unavailable for too-many images
      connect_timeout_ms: 1500
    self_host:
      host: "https://bef-cd.fseasy.top"
      port: 19981
      connect_timeout_ms: 500
  production_service_try_order: 
    - self_host
    - cf_cdn
    - vercel

# Waline comments
waline:
  serverURL: "https://waline.fseasy.top"
