# Site settings
title: 小文件
email: readonlyfile@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
   我的个人空间 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://memeda.github.io" # the base hostname & protocol for your site
twitter_username: memeda
github_username:  memeda

# Build settings
markdown: kramdown
