# Site settings
title: 鱼虾写字
email: readonlyfile@hotmail.com
# GEM which uses `github-pages` is dependend on github repo. set this var is necessary when repo's `url` don't contain
# repository field. (such as, we change the dns name `github.com` => ip port in repo's url)
repository: fseasy/blog.git
description: > # this means to ignore newlines until "baseurl:"
  不必太悲观
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.fseasy.top" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins: 
  - jekyll-paginate
  - jekyll-sitemap

exclude: [_site, md_templates_, deployment_]
paginate: 15

#social info
github_username: fseasy

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:month/:title/

sass:
    style: compressed
    sass_dir: assets/css/_sass
