#!uv run
"""
Create a new blog post with the given title slug.

Usage:
  uv run python new_post.py reading fusheng
  uv run python new_post.py reading-fusheng
  uv run python new_post.py "reading fusheng"

The slug is generated by merging all arguments, converting spaces/underscores
to hyphens, and sanitizing special characters.
"""

import re
import sys
from datetime import datetime
from pathlib import Path

POSTS_DIR = (Path(__file__).parent.parent / "_posts").resolve()

TEMPLATE = """---
layout: post
title:
date: {date}
categories: WLR / 杂谈 / 技术
tags:
---

>
"""


def make_slug(*parts):
    """Merge parts and convert to a safe filename slug."""
    text = " ".join(parts)
    text = re.sub(r"[-_\s]+", " ", text)
    text = text.lower().strip()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text)
    text = re.sub(r"-+", "-", text)
    text = text.strip("-")
    return text


def get_decade_prefix(year):
    """Get decade prefix like 201x or 202x."""
    decade = (year // 10)
    return f"{decade}x"


def create_post(slug):
    """Create a new post file with the given slug."""
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    filename = f"{date_str}-{slug}.md"
    year = now.year
    decade_prefix = get_decade_prefix(year)

    post_dir = POSTS_DIR / decade_prefix / str(year)
    post_dir.mkdir(parents=True, exist_ok=True)

    filepath = post_dir / filename
    content = TEMPLATE.format(date=date_str)
    filepath.write_text(content)
    print(f"Created: {filepath}")
    return filepath


def main():
    if len(sys.argv) < 2:
        print("Usage: python new_post.py <title>...")
        print("Example: python new_post.py reading fusheng")
        sys.exit(1)

    slug = make_slug(*sys.argv[1:])
    if not slug:
        print("Error: empty slug after sanitization")
        sys.exit(1)

    create_post(slug)


if __name__ == "__main__":
    main()
